// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Breadcrumb: typeof import('./src/components/breadcrumb/Breadcrumb.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    Notification: typeof import('./src/components/notification/Notification.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToastEditor: typeof import('./src/components/markdown/ToastEditor.vue')['default']
    TwButton: typeof import('./src/components/form/TwButton.vue')['default']
    TwInput: typeof import('./src/components/form/TwInput.vue')['default']
    TwLink: typeof import('./src/components/form/TwLink.vue')['default']
    TwTransition: typeof import('./src/components/transition/TwTransition.vue')['default']
  }
}

export {}
