// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AnimateList: typeof import('./../src/components/AnimateList.vue')['default']
    MarkdownEditor: typeof import('./../src/components/Markdown/Editor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TransitionTwTransition: typeof import('./../src/components/transition/TwTransition.vue')['default']
    TwBreadcrumb: typeof import('./../src/components/Tw/Breadcrumb.vue')['default']
    TwButton: typeof import('./../src/components/Tw/Button.vue')['default']
    TwInput: typeof import('./../src/components/Tw/Input.vue')['default']
    TwLink: typeof import('./../src/components/Tw/Link.vue')['default']
    TwNotification: typeof import('./../src/components/Tw/Notification.vue')['default']
    WangEditorEditor: typeof import('./../src/components/WangEditor/Editor.vue')['default']
  }
}

export {}
